Repository xedi/sdk-js, pull requests merged in 2020-06, with the labels that each got.

#52 Added the documentation for usage/translations
  docs/content/usage/translations.mdx
  docs/gatsby-node.js
  docs/src/@primer/gatsby-theme-doctocat/nav.yml
  docs/src/components/index.js
  docs/src/components/translations_reference.js
Labels: documentation, enhancement

#55 Adds get user permissions
  src/Models/Models.ts
  src/Models/Permission.ts
  src/Services/Users.ts
Labels: enhancement

#64 Initial pass at the contribution sections of the documentation
  docs/content/about/contributing.mdx
  docs/content/documentation/contributing.md
  docs/gatsby-node.js
  docs/src/@primer/gatsby-theme-doctocat/nav.yml
  docs/src/components/blankslate.js
  docs/src/components/github_issues.js
  docs/src/components/index.js
Labels: documentation

#66 [#65] Improved the documented responses to the Auth api
  docs/content/usage/auth.mdx
Labels: documentation

#67 Usage for Businesses API
  docs/content/usage/businesses.mdx
Labels: documentation
